language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd demo && mvn clean install com.updateimpact:updateimpact-maven-plugin:submit -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U